// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.se;

import com.se.Sadasdasd;

privileged aspect Sadasdasd_Roo_JavaBean {
    
    public String Sadasdasd.getName() {
        return this.name;
    }
    
    public void Sadasdasd.setName(String name) {
        this.name = name;
    }
    
}
